### ISSUE TITLE
Bug : 닉네임 중복 처리하는 조건문 오류

### ISSUE THREAD

**Issue by codekmj1** [HwangSeungHyeon/buysell#57]
## 어떤 버그인가요 ?
-  조건문에서 DB를 조회 후 중복 닉네임이 존재하면 true로 반환해야 하는데 false로 반환된다

## 발생 상황
- when : 회원가입 테스트 중

- then : 닉네임 중복 테스트를 한다

- given : DB에 닉네임이 존재할 때 조건문에서 true로 반환하지 않고 false로 반환된다.

## 예상 결과
- DB에 닉네임이 존재한다면 조건문 결과가 true로 반환됨

**Comment by HwangSeungHyeon** [comment]
확인 결과 데이터베이스와의 동기화 문제였습니다.
ddl-auto: create 로 데이터 테이블을 다시 만들고, 코드를 재실행하니 정상 작동하는 모습을 확인했습니다.
